// Mock data for the admin panel

export const mockUsers = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-04-15T12:00:00Z',
    lastActive: '2023-11-05T09:45:00Z',
    verified: true,
  },
  {
    id: '2',
    name: 'Emma Smith',
    email: 'emma@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-05-20T10:30:00Z',
    lastActive: '2023-11-04T14:22:00Z',
    verified: true,
  },
  {
    id: '3',
    name: 'Michael Johnson',
    email: 'michael@example.com',
    status: 'inactive',
    role: 'user',
    joinedAt: '2023-03-10T09:15:00Z',
    lastActive: '2023-10-01T11:33:00Z',
    verified: false,
  },
  {
    id: '4',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    status: 'banned',
    role: 'user',
    joinedAt: '2023-01-05T14:45:00Z',
    lastActive: '2023-09-15T16:47:00Z',
    verified: true,
  },
  {
    id: '5',
    name: 'James Brown',
    email: 'james@example.com',
    status: 'active',
    role: 'moderator',
    joinedAt: '2023-02-18T08:20:00Z',
    lastActive: '2023-11-06T10:15:00Z',
    verified: true,
  },
  {
    id: '6',
    name: 'Jessica Davis',
    email: 'jessica@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-06-22T13:10:00Z',
    lastActive: '2023-11-03T17:30:00Z',
    verified: true,
  },
  {
    id: '7',
    name: 'Robert Miller',
    email: 'robert@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-07-11T11:55:00Z',
    lastActive: '2023-11-01T09:20:00Z',
    verified: true,
  },
  {
    id: '8',
    name: 'Jennifer Wilson',
    email: 'jennifer@example.com',
    status: 'inactive',
    role: 'user',
    joinedAt: '2023-08-30T15:40:00Z',
    lastActive: '2023-10-10T14:05:00Z',
    verified: false,
  },
  {
    id: '9',
    name: 'Thomas Moore',
    email: 'thomas@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-09-14T10:25:00Z',
    lastActive: '2023-11-02T11:45:00Z',
    verified: true,
  },
  {
    id: '10',
    name: 'Linda Taylor',
    email: 'linda@example.com',
    status: 'active',
    role: 'user',
    joinedAt: '2023-10-05T12:35:00Z',
    lastActive: '2023-11-06T08:55:00Z',
    verified: true,
  },
];

export const mockExperts = [
  {
    id: '1',
    name: 'Dr. Alice Johnson',
    email: 'alice@example.com',
    category: 'Health & Wellness',
    status: 'active',
    profileCompletion: 100,
    followers: 1250,
    joinedAt: '2023-01-10T09:00:00Z',
    lastActive: '2023-11-06T08:30:00Z',
    verified: true,
    featured: true,
    experience: '15 years of experience in holistic health and wellness',
    skills: ['Nutrition', 'Yoga', 'Meditation', 'Stress Management']
  },
  {
    id: '2',
    name: 'Prof. David Wilson',
    email: 'david@example.com',
    category: 'Education',
    status: 'active',
    profileCompletion: 90,
    followers: 850,
    joinedAt: '2023-02-15T10:30:00Z',
    lastActive: '2023-11-05T14:15:00Z',
    verified: true,
    featured: false,
    experience: '20 years in education and curriculum development',
    skills: ['Teaching', 'Curriculum Design', 'Educational Technology', 'Student Assessment']
  },
  {
    id: '3',
    name: 'Chef Marco Rodriguez',
    email: 'marco@example.com',
    category: 'Culinary Arts',
    status: 'active',
    profileCompletion: 95,
    followers: 2200,
    joinedAt: '2023-03-20T11:45:00Z',
    lastActive: '2023-11-06T10:20:00Z',
    verified: true,
    featured: true,
    experience: '12 years in professional cooking and restaurant management',
    skills: ['Italian Cuisine', 'Pastry', 'Menu Planning', 'Food Safety']
  },
  {
    id: '4',
    name: 'Rebecca Chen',
    email: 'rebecca@example.com',
    category: 'Technology',
    status: 'pending',
    profileCompletion: 75,
    followers: 320,
    joinedAt: '2023-09-05T14:00:00Z',
    lastActive: '2023-11-04T16:45:00Z',
    verified: false,
    featured: false,
    experience: '8 years in software development and AI research',
    skills: ['Machine Learning', 'Python', 'Data Analysis', 'Cloud Computing']
  },
  {
    id: '5',
    name: 'Samuel Jackson',
    email: 'samuel@example.com',
    category: 'Financial Planning',
    status: 'active',
    profileCompletion: 100,
    followers: 945,
    joinedAt: '2023-04-30T09:15:00Z',
    lastActive: '2023-11-01T13:30:00Z',
    verified: true,
    featured: false,
    experience: '18 years in financial advisory and wealth management',
    skills: ['Investment Planning', 'Retirement Planning', 'Tax Strategy', 'Risk Management']
  },
  {
    id: '6',
    name: 'Olivia Martinez',
    email: 'olivia@example.com',
    category: 'Fitness',
    status: 'inactive',
    profileCompletion: 85,
    followers: 1500,
    joinedAt: '2023-05-12T10:00:00Z',
    lastActive: '2023-10-15T11:20:00Z',
    verified: true,
    featured: false,
    experience: '10 years in personal training and fitness coaching',
    skills: ['Strength Training', 'HIIT', 'Nutrition', 'Injury Prevention']
  },
  {
    id: '7',
    name: 'William Thompson',
    email: 'william@example.com',
    category: 'Legal Advice',
    status: 'active',
    profileCompletion: 95,
    followers: 720,
    joinedAt: '2023-06-22T13:45:00Z',
    lastActive: '2023-11-03T09:10:00Z',
    verified: true,
    featured: false,
    experience: '14 years practicing corporate law',
    skills: ['Contract Law', 'Corporate Governance', 'Mergers & Acquisitions', 'Compliance']
  },
  {
    id: '8',
    name: 'Sophia Lee',
    email: 'sophia@example.com',
    category: 'Fashion & Style',
    status: 'active',
    profileCompletion: 100,
    followers: 3100,
    joinedAt: '2023-07-18T11:30:00Z',
    lastActive: '2023-11-06T15:25:00Z',
    verified: true,
    featured: true,
    experience: '9 years in fashion design and styling',
    skills: ['Fashion Design', 'Personal Styling', 'Trend Analysis', 'Brand Development']
  },
  {
    id: '9',
    name: 'Daniel Clark',
    email: 'daniel@example.com',
    category: 'Home Improvement',
    status: 'pending',
    profileCompletion: 60,
    followers: 450,
    joinedAt: '2023-10-05T15:15:00Z',
    lastActive: '2023-11-02T10:40:00Z',
    verified: false,
    featured: false,
    experience: '7 years in home renovation and interior design',
    skills: ['Carpentry', 'Interior Design', 'Project Management', 'Sustainable Building']
  },
  {
    id: '10',
    name: 'Emily Davis',
    email: 'emily@example.com',
    category: 'Mental Health',
    status: 'active',
    profileCompletion: 90,
    followers: 1780,
    joinedAt: '2023-08-30T12:00:00Z',
    lastActive: '2023-11-04T08:55:00Z',
    verified: true,
    featured: false,
    experience: '11 years in clinical psychology and counseling',
    skills: ['Cognitive Behavioral Therapy', 'Anxiety Management', 'Stress Reduction', 'Mindfulness']
  },
];

export const mockPosts = [
  {
    id: '1',
    expertId: '1',
    expertName: 'Dr. Alice Johnson',
    title: 'The Importance of Daily Exercise',
    content: 'Regular physical activity has numerous benefits for your health...',
    category: 'Health & Wellness',
    status: 'published',
    createdAt: '2023-10-15T09:30:00Z',
    likes: 245,
    comments: 32,
  },
  {
    id: '2',
    expertId: '3',
    expertName: 'Chef Marco Rodriguez',
    title: 'Quick and Healthy Breakfast Ideas',
    content: 'Start your day right with these nutritious breakfast recipes...',
    category: 'Culinary Arts',
    status: 'published',
    createdAt: '2023-11-01T11:15:00Z',
    likes: 189,
    comments: 27,
  },
  {
    id: '3',
    expertId: '8',
    expertName: 'Sophia Lee',
    title: 'Winter Fashion Trends 2023',
    content: 'Discover the latest fashion trends for the upcoming winter season...',
    category: 'Fashion & Style',
    status: 'published',
    createdAt: '2023-11-05T14:00:00Z',
    likes: 312,
    comments: 45,
  },
  {
    id: '4',
    expertId: '4',
    expertName: 'Rebecca Chen',
    title: 'Introduction to Machine Learning',
    content: 'Learn the basic concepts of machine learning and its applications...',
    category: 'Technology',
    status: 'pending',
    createdAt: '2023-11-06T10:45:00Z',
    likes: 0,
    comments: 0,
  },
  {
    id: '5',
    expertId: '5',
    expertName: 'Samuel Jackson',
    title: 'Saving for Retirement: Early Planning',
    content: 'The importance of starting your retirement planning early...',
    category: 'Financial Planning',
    status: 'published',
    createdAt: '2023-10-28T13:20:00Z',
    likes: 156,
    comments: 19,
  },
  {
    id: '6',
    expertId: '10',
    expertName: 'Emily Davis',
    title: 'Managing Anxiety in Daily Life',
    content: 'Effective strategies to cope with anxiety in everyday situations...',
    category: 'Mental Health',
    status: 'flagged',
    createdAt: '2023-11-02T16:10:00Z',
    likes: 203,
    comments: 37,
  },
  {
    id: '7',
    expertId: '6',
    expertName: 'Olivia Martinez',
    title: 'At-Home Workout Routines',
    content: 'Stay fit with these effective home workout routines...',
    category: 'Fitness',
    status: 'published',
    createdAt: '2023-09-20T09:00:00Z',
    likes: 278,
    comments: 41,
  },
  {
    id: '8',
    expertId: '7',
    expertName: 'William Thompson',
    title: 'Understanding Tenant Rights',
    content: 'What every tenant should know about their legal rights...',
    category: 'Legal Advice',
    status: 'pending',
    createdAt: '2023-11-04T11:30:00Z',
    likes: 0,
    comments: 0,
  },
  {
    id: '9',
    expertId: '2',
    expertName: 'Prof. David Wilson',
    title: 'Effective Study Techniques for Students',
    content: 'Improve your learning with these proven study methods...',
    category: 'Education',
    status: 'published',
    createdAt: '2023-10-10T15:45:00Z',
    likes: 167,
    comments: 23,
  },
  {
    id: '10',
    expertId: '9',
    expertName: 'Daniel Clark',
    title: 'DIY Home Renovation Tips',
    content: 'Save money with these do-it-yourself home improvement ideas...',
    category: 'Home Improvement',
    status: 'pending',
    createdAt: '2023-11-03T12:15:00Z',
    likes: 0,
    comments: 0,
  },
];

export const mockReports = [
  {
    id: '1',
    targetType: 'post',
    targetId: '6',
    reportedBy: 'John Doe',
    reason: 'Inappropriate content',
    description: 'This post contains potentially triggering content without proper warnings.',
    status: 'pending',
    createdAt: '2023-11-03T09:15:00Z',
    priority: 'high',
  },
  {
    id: '2',
    targetType: 'user',
    targetId: '4',
    reportedBy: 'Emma Smith',
    reason: 'Harassment',
    description: 'This user has been sending threatening messages to multiple people.',
    status: 'pending',
    createdAt: '2023-11-05T11:30:00Z',
    priority: 'high',
  },
  {
    id: '3',
    targetType: 'post',
    targetId: '2',
    reportedBy: 'Michael Johnson',
    reason: 'Misinformation',
    description: 'This post contains nutritional advice that contradicts established medical guidelines.',
    status: 'resolved',
    createdAt: '2023-11-01T14:45:00Z',
    priority: 'medium',
    resolvedAt: '2023-11-02T10:20:00Z',
    resolution: 'Content edited with correct information',
  },
  {
    id: '4',
    targetType: 'expert',
    targetId: '9',
    reportedBy: 'Sarah Williams',
    reason: 'Misrepresentation',
    description: 'This expert claims credentials that appear to be fabricated.',
    status: 'pending',
    createdAt: '2023-11-04T16:10:00Z',
    priority: 'high',
  },
  {
    id: '5',
    targetType: 'comment',
    targetId: '101',
    targetParentId: '3',
    reportedBy: 'James Brown',
    reason: 'Spam',
    description: 'This comment contains promotional links to unrelated commercial websites.',
    status: 'pending',
    createdAt: '2023-11-06T08:30:00Z',
    priority: 'low',
  },
  {
    id: '6',
    targetType: 'post',
    targetId: '7',
    reportedBy: 'Jessica Davis',
    reason: 'Dangerous content',
    description: 'This workout routine suggests exercises that could be harmful without proper instruction.',
    status: 'resolved',
    createdAt: '2023-10-25T13:20:00Z',
    priority: 'medium',
    resolvedAt: '2023-10-26T09:15:00Z',
    resolution: 'Added safety warnings and modified exercises',
  },
  {
    id: '7',
    targetType: 'user',
    targetId: '8',
    reportedBy: 'Robert Miller',
    reason: 'Inappropriate username',
    description: 'This username contains offensive language.',
    status: 'resolved',
    createdAt: '2023-11-02T10:05:00Z',
    priority: 'low',
    resolvedAt: '2023-11-02T15:30:00Z',
    resolution: 'User required to change username',
  },
  {
    id: '8',
    targetType: 'expert',
    targetId: '4',
    reportedBy: 'Jennifer Wilson',
    reason: 'Misleading advice',
    description: 'This expert has been providing technology recommendations that appear to be sponsored without disclosure.',
    status: 'pending',
    createdAt: '2023-11-03T11:45:00Z',
    priority: 'medium',
  },
  {
    id: '9',
    targetType: 'comment',
    targetId: '205',
    targetParentId: '1',
    reportedBy: 'Thomas Moore',
    reason: 'Hate speech',
    description: 'This comment contains derogatory language targeting specific groups.',
    status: 'pending',
    createdAt: '2023-11-05T12:40:00Z',
    priority: 'high',
  },
  {
    id: '10',
    targetType: 'post',
    targetId: '10',
    reportedBy: 'Linda Taylor',
    reason: 'Copyright infringement',
    description: 'This post contains images and text that appear to be copied from a professional publication without attribution.',
    status: 'pending',
    createdAt: '2023-11-06T09:55:00Z',
    priority: 'medium',
  },
];

export const analyticsData = {
  userGrowth: [
    { month: 'Jan', count: 450 },
    { month: 'Feb', count: 550 },
    { month: 'Mar', count: 620 },
    { month: 'Apr', count: 750 },
    { month: 'May', count: 890 },
    { month: 'Jun', count: 1020 },
    { month: 'Jul', count: 1180 },
    { month: 'Aug', count: 1320 },
    { month: 'Sep', count: 1450 },
    { month: 'Oct', count: 1580 },
    { month: 'Nov', count: 1720 },
  ],
  expertGrowth: [
    { month: 'Jan', count: 20 },
    { month: 'Feb', count: 35 },
    { month: 'Mar', count: 45 },
    { month: 'Apr', count: 60 },
    { month: 'May', count: 80 },
    { month: 'Jun', count: 95 },
    { month: 'Jul', count: 110 },
    { month: 'Aug', count: 130 },
    { month: 'Sep', count: 145 },
    { month: 'Oct', count: 160 },
    { month: 'Nov', count: 178 },
  ],
  engagementMetrics: {
    averageDailyActiveUsers: 820,
    averageSessionDuration: '9m 45s',
    averageActionsPerSession: 12.3,
    chatCompletionRate: 87.5,
  },
  topCategories: [
    { name: 'Health & Wellness', experts: 42, users: 3200 },
    { name: 'Technology', experts: 35, users: 2800 },
    { name: 'Financial Planning', experts: 28, users: 2450 },
    { name: 'Education', experts: 25, users: 2100 },
    { name: 'Fitness', experts: 24, users: 1950 },
  ],
  contentActivity: {
    totalPosts: 3450,
    postsLastMonth: 320,
    averageLikesPerPost: 145,
    averageCommentsPerPost: 23,
  },
  reportStatistics: {
    totalReports: 245,
    openReports: 68,
    averageResolutionTime: '28 hours',
    mostCommonReason: 'Misinformation',
  },
};